## This runs testme test script inst/testme/test-mirai_cluster,worker-termination.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
future.mirai:::testme("mirai_cluster,worker-termination")
