## This runs testme test script inst/testme/test-future.tests-mirai_multisession.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
future.mirai:::testme("future.tests-mirai_multisession")
